### ISSUE TITLE
Arrow keys show `[ Unbound key ]` error

### ISSUE THREAD

**Issue by rasa** [okibcn/nano-for-windows#10]
Inside an ssh session (via `OpenSSH_for_Windows_9.1p1, LibreSSL 3.6.1`) and running nano 7.2-10-10165, when I press any arrow key, the error `[ Unbound key ]` appears. **Edit:** The PgUp, PgDn, Home and End keys work fine.

This doesn't happen running git-for-windows' nano version inside an ssh session.

This doesn't happen running nano 7.2-10-10165 in a CMD window or wt window.

Any ideas?

**Comment by okibcn** [comment]
Yes, key assignments change when using terminal and when using local console host. I will look into that.

**Comment by okibcn** [comment]
Fixed in release  [v7.2-10-10165.1](https://github.com/okibcn/nano-for-windows/releases/tag/v7.2-10-10165.1).

The decision on departing from Virtual Terminal Emulation and using direct console access in [v7.2-9-10164.3](https://github.com/okibcn/nano-for-windows/releases/tag/v7.2-9-10164.3) was tasked due to the limitation of ANSI mode to display transparent backgrounds. It had two important side effects:
1. corruption in Windows Terminal when using some Unicode planes.
2. loss of pure terminal features such as working through ssh.

The current fix for ANSI mode has allowed the return to the original terminal emulation mode, solving those two nasty problemas.

**Comment by rasa** [comment]
@okibcn I just tested [v7.2-10-10165.1](https://github.com/okibcn/nano-for-windows/releases/tag/v7.2-10-10165.1), and I am still seeing `[ Unbound key ]` messages with [Up], [Down], [Left], [Right], [Del], [Ins], [Ctrl-Enter], [Ctrl-Home], and [Ctrtl-End]. It doesn't appear with [PgUp], [PgDn], [Home], [End], [Backspace], [Tab] and [Esc], or most [Shift/Ctrl/Alt] variations thereof. Here's a screenshot after pressing [Down]:
![9FB91176-02DB-40BB-85C3-E0E80320F98E](https://user-images.githubusercontent.com/220772/218615438-187a90aa-438a-48b2-b867-b367ff73ef6d.jpeg)

**Comment by okibcn** [comment]
I have tested it with the Tmate debug action in Github and the latest version doesn't show that problem. I am using the OpenSSH client that comes with Windows 11. I am in the dev preview channel using Windows version 10.0.25295.1000, and the SSH.EXE binary is in version 8.9.1.1.

I am not sure about the version of Tmate SSH server used by the Github Action. Which SSH server are you using?

**Comment by rasa** [comment]
It's `OpenSSH_for_Windows_9.1p1, LibreSSL 3.6.1` installed on Windows 10 x64 22H2 via winget:
```
> winget search openssh  
Name         Id                     Version Source
---------------------------------------------------
OpenSSH Beta Microsoft.OpenSSH.Beta 9.1.0.0 winget

> ver

Microsoft Windows [Version 10.0.19045.2546]
```
Surprisingly, winget doesn't offer a non-beta version.

If you can't duplicate the issue, let's leave this closed and let me try some different ssh servers to see if they exhibit this issue.

**Comment by okibcn** [comment]
I just tested it using the ssh client from Ubuntu and it works as if it was local.

In this session, you can see how:
1. I connect to Tmate server.
2. open a remote cmd.exe prompt.
3. Download [v7.2-10-10165.1](https://github.com/okibcn/nano-for-windows/releases/tag/v7.2-10-10165.1)
4. unzip it
5. change to the bin folder
6. open nano with forced defaults (`nano-I`)
7. I type some numbers and I move in all directions with arrows and PgUp, PgDw.

[![asciicast](https://asciinema.org/a/RSp1I0QAXbCo0Z8KF8QaQY01Z.svg)](https://asciinema.org/a/RSp1I0QAXbCo0Z8KF8QaQY01Z)


I am really curious about this issue. I will try to duplicate it.

**Comment by rasa** [comment]
***Test 1: OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2***
Running:
  `C:\Windows\System32\OpenSSH\sshd.exe -D -d`
I found:
`C:\Program Files\Git\usr\bin\nano.exe -I` works and
`C:\Users\ross\scoop\apps\nano\7.2-10-10165.1\nano.exe -I` fails with `[ Unbound key ]`
will try `C:\Program Files\Git\usr\bin\sshd.exe` but that daemon spawns bash, not a cmd shell.

**Comment by rasa** [comment]
**Test2: OpenSSH_9.1, OpenSSL 1.1.1s  1 Nov 2022**
Running:
`"C:\Program Files\Git\usr\bin\sshd.exe" -D -d`
I found:
`/usr/bin/nano.exe -I` works and
`~/scoop/apps/nano/7.2-10-10165.1/nano.exe -I` emits
`Redirection is not supported.`
and quits.

**Comment by okibcn** [comment]
I have tested connecting from linux and from Windows to Tmate and both work. So, the issue must be in the server. I don't have the setup for Windows, usually I connect to my OpenWrt and other devices through ssh, but not the opposite. But It should work also when the remote shell is not bash, or MinGW-Bash.

**Comment by rasa** [comment]
I'm not surprised Microsoft's implementation of OpenSSH is flawed, but somehow git-for-windows version of nano works around the issue. Do you know where git-for-windows' nano patches live? I've poked around https://github.com/git-for-windows/build-extra but haven't found anything.

**Comment by okibcn** [comment]
Well, I have installed the OpenSSH you mentioned in winget with `winget install Microsoft.OpenSSH.Beta`
then I tested accessing locally with ssh localhost, and remotely from a Linux machine. Both work perfectly:

[![asciicast](https://asciinema.org/a/UUy4R10kSGRHOjGYzoO9Ma1IG.svg)](https://asciinema.org/a/UUy4R10kSGRHOjGYzoO9Ma1IG)


So, I still can't duplicate the issue.

**Comment by rasa** [comment]
OK, Lemme test on another system. I appreciate your patience as I work thru this. I'm gonna close this issue for now.

**Comment by okibcn** [comment]
By the way, even the mouse works fine.

**Comment by okibcn** [comment]
In the last [release 7.2-13.2](https://github.com/okibcn/nano-for-windows/releases/tag/v7.2-13.2), I fixed some key mappings. It solves CTRL+arrows and CTRL+Home/End among other fixes. Maybe your issue was related to those keys.

**Comment by rasa** [comment]
Still not working on system A. Haven't yet tested on system B.

**Comment by okibcn** [comment]
I am curious about your setup. I have been using this through SSH, tmux, and it always works. Can it be a problem with the terminal app you use?

**Comment by rasa** [comment]
> I am curious about your setup. I have been using this through SSH, tmux, and it always works. Can it be a problem with the terminal app you use?

I have tried four different ones. I think it’s a bug in Microsoft’s port of OpenSSH. Once I test with other SSH daemons and on other systems, I will update this thread.

**Comment by rasa** [comment]
@okibcn I installed Bitvise's SSH server from https://www.bitvise.com/ssh-server, and the arrow keys worked fine. I will do some more testing with Microsoft's OpenSSH port, but it's clearly the culprit here.

**Comment by okibcn** [comment]
Thanks for the update. I tried to duplicate the issue. It could be related to the UTF-8/WIDE support. The rest of the nano versions for windows are not actually using wide chars. Some versions report UTF-8 as enabled, but when using the nimibar inside nano, you can see that they do not actually use wchar at all. You can easily see it as the current chat is not denoted by U+HHHH (four hex digits) but only U+HH.

I suspect that incompatibility with UTF-8 could be causing your issue, Maybe the SSH software, or the terminal app you are using  can't understand the 16 bit control codes encoded as UTF-8.

**Comment by sdrapha** [comment]
Same issue here, it's still an active issue.

Running nano in windows, if I'm local, nano works fine, but if I SSH into it, nano key binds doesn't work at all. 

Even if I ssh into localhost, to eliminate any external variables.

Also tested in WT and CMD, no difference. So the terminal is not the problem.

The only common factor is the SSH connection.

But before we push the issue to openssh court. 
I can used Micro just fine both in and out of a ssh connection. So that shows that maybe it's something with Nano itself.

I would like to keep this issue reopened.

**Comment by sdrapha** [comment]
extra info - host running:
Windows 10 Pro 22H2 build 19045.3448
OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2
GNU nano for Windows 64 bits, v7.2-22.1 2023.04.15

**Comment by Dr-Electron** [comment]
I also can't get it to work with the beta. Also not working in WSL. Anyone got a solution or something I could try?

**Comment by kmowledge** [comment]
As someone already said: 
Use Micro instead of nano (choco install micro), no issues with cursors, syntax highlighting etc.
Nano = 8* years, no solution
![image](https://github.com/user-attachments/assets/ca06782a-3ccb-497a-b8b3-c31738cbc730)
credits: [artisticcheese](https://github.com/artisticcheese)

**Comment by rasa** [comment]
> As someone already said: Use Micro instead of nano

@kmowledge Does micro support Unicode? Have you used it inside an SSH session in Windows?

**Comment by kmowledge** [comment]
@rasa  It does support unicode. Not sure if that's what you're asking about, but: I communicate with github on ssh from git bash terminal within vs code. And I've just used micro to edit some file contents before making a commit. No issues.
